from enum import IntEnum


class PacketTag(IntEnum):
    # RFC 4880 section 4.3 / RFC 9580 section 5
    PUBLIC_KEY_ENCRYPTED_SESSION_KEY = 1
    SIGNATURE = 2
    SYMMETRIC_KEY_ENCRYPTED_SESSION_KEY = 3
    ONE_PASS_SIGNATURE = 4
    SECRET_KEY = 5
    PUBLIC_KEY = 6
    SECRET_SUBKEY = 7
    COMPRESSED_DATA = 8
    SYMMETRICALLY_ENCRYPTED_DATA = 9
    MARKER = 10
    LITERAL_DATA = 11
    TRUST = 12
    USER_ID = 13
    PUBLIC_SUBKEY = 14
    USER_ATTRIBUTE = 17
    SYMMETRICALLY_ENCRYPTED_INTEGRITY_PROTECTED_DATA = 18
    MODIFICATION_DETECTION_CODE = 19
    # RFC 9580 additions
    PADDING = 21
